# Site settings
title: Chorale Sainte Philomene
email: csp-mavigne@gmail.com
description: > # site de la chorale Sainte Philomène.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://csp-mavigne.org" # the base hostname & protocol for your site
github_username:  csp-vigne

# Build settings
markdown: kramdown
highlighter: rouge
#pygments: rouge
